# Curated pool of FREE (non-premium) LeetCode problems.
# Format: (slug, title, difficulty)
# Slug maps to https://leetcode.com/problems/<slug>/

POOL = {
"Arrays & Hashing": [
 ("two-sum","Two Sum","Easy"),
 ("contains-duplicate","Contains Duplicate","Easy"),
 ("valid-anagram","Valid Anagram","Easy"),
 ("majority-element","Majority Element","Easy"),
 ("single-number","Single Number","Easy"),
 ("missing-number","Missing Number","Easy"),
 ("move-zeroes","Move Zeroes","Easy"),
 ("plus-one","Plus One","Easy"),
 ("remove-element","Remove Element","Easy"),
 ("remove-duplicates-from-sorted-array","Remove Duplicates from Sorted Array","Easy"),
 ("merge-sorted-array","Merge Sorted Array","Easy"),
 ("intersection-of-two-arrays","Intersection of Two Arrays","Easy"),
 ("intersection-of-two-arrays-ii","Intersection of Two Arrays II","Easy"),
 ("find-all-numbers-disappeared-in-an-array","Find All Numbers Disappeared in an Array","Easy"),
 ("running-sum-of-1d-array","Running Sum of 1d Array","Easy"),
 ("find-pivot-index","Find Pivot Index","Easy"),
 ("range-sum-query-immutable","Range Sum Query - Immutable","Easy"),
 ("pascals-triangle","Pascal's Triangle","Easy"),
 ("contains-duplicate-ii","Contains Duplicate II","Easy"),
 ("can-place-flowers","Can Place Flowers","Easy"),
 ("third-maximum-number","Third Maximum Number","Easy"),
 ("summary-ranges","Summary Ranges","Easy"),
 ("group-anagrams","Group Anagrams","Medium"),
 ("top-k-frequent-elements","Top K Frequent Elements","Medium"),
 ("product-of-array-except-self","Product of Array Except Self","Medium"),
 ("valid-sudoku","Valid Sudoku","Medium"),
 ("maximum-subarray","Maximum Subarray","Medium"),
 ("maximum-product-subarray","Maximum Product Subarray","Medium"),
 ("subarray-sum-equals-k","Subarray Sum Equals K","Medium"),
 ("set-matrix-zeroes","Set Matrix Zeroes","Medium"),
 ("spiral-matrix","Spiral Matrix","Medium"),
 ("rotate-image","Rotate Image","Medium"),
 ("rotate-array","Rotate Array","Medium"),
 ("sort-colors","Sort Colors","Medium"),
 ("next-permutation","Next Permutation","Medium"),
 ("longest-consecutive-sequence","Longest Consecutive Sequence","Medium"),
 ("first-missing-positive","First Missing Positive","Hard"),
],
"Two Pointers": [
 ("valid-palindrome","Valid Palindrome","Easy"),
 ("two-sum-ii-input-array-is-sorted","Two Sum II - Input Array Is Sorted","Medium"),
 ("squares-of-a-sorted-array","Squares of a Sorted Array","Easy"),
 ("backspace-string-compare","Backspace String Compare","Easy"),
 ("reverse-string","Reverse String","Easy"),
 ("is-subsequence","Is Subsequence","Easy"),
 ("3sum","3Sum","Medium"),
 ("3sum-closest","3Sum Closest","Medium"),
 ("4sum","4Sum","Medium"),
 ("container-with-most-water","Container With Most Water","Medium"),
 ("boats-to-save-people","Boats to Save People","Medium"),
 ("partition-labels","Partition Labels","Medium"),
 ("trapping-rain-water","Trapping Rain Water","Hard"),
],
"Sliding Window": [
 ("best-time-to-buy-and-sell-stock","Best Time to Buy and Sell Stock","Easy"),
 ("maximum-average-subarray-i","Maximum Average Subarray I","Easy"),
 ("longest-substring-without-repeating-characters","Longest Substring Without Repeating Characters","Medium"),
 ("longest-repeating-character-replacement","Longest Repeating Character Replacement","Medium"),
 ("permutation-in-string","Permutation in String","Medium"),
 ("find-all-anagrams-in-a-string","Find All Anagrams in a String","Medium"),
 ("minimum-size-subarray-sum","Minimum Size Subarray Sum","Medium"),
 ("fruit-into-baskets","Fruit Into Baskets","Medium"),
 ("max-consecutive-ones-iii","Max Consecutive Ones III","Medium"),
 ("longest-subarray-of-1s-after-deleting-one-element","Longest Subarray of 1's After Deleting One Element","Medium"),
 ("minimum-window-substring","Minimum Window Substring","Hard"),
 ("sliding-window-maximum","Sliding Window Maximum","Hard"),
 ("subarrays-with-k-different-integers","Subarrays with K Different Integers","Hard"),
],
"Strings": [
 ("longest-common-prefix","Longest Common Prefix","Easy"),
 ("ransom-note","Ransom Note","Easy"),
 ("first-unique-character-in-a-string","First Unique Character in a String","Easy"),
 ("isomorphic-strings","Isomorphic Strings","Easy"),
 ("word-pattern","Word Pattern","Easy"),
 ("add-binary","Add Binary","Easy"),
 ("roman-to-integer","Roman to Integer","Easy"),
 ("repeated-substring-pattern","Repeated Substring Pattern","Easy"),
 ("find-the-index-of-the-first-occurrence-in-a-string","Find the Index of the First Occurrence in a String","Easy"),
 ("length-of-last-word","Length of Last Word","Easy"),
 ("reverse-words-in-a-string","Reverse Words in a String","Medium"),
 ("string-to-integer-atoi","String to Integer (atoi)","Medium"),
 ("integer-to-roman","Integer to Roman","Medium"),
 ("multiply-strings","Multiply Strings","Medium"),
 ("zigzag-conversion","Zigzag Conversion","Medium"),
 ("longest-palindromic-substring","Longest Palindromic Substring","Medium"),
 ("palindromic-substrings","Palindromic Substrings","Medium"),
 ("sort-characters-by-frequency","Sort Characters By Frequency","Medium"),
 ("count-and-say","Count and Say","Medium"),
],
"Stack": [
 ("valid-parentheses","Valid Parentheses","Easy"),
 ("min-stack","Min Stack","Medium"),
 ("implement-queue-using-stacks","Implement Queue using Stacks","Easy"),
 ("implement-stack-using-queues","Implement Stack using Queues","Easy"),
 ("baseball-game","Baseball Game","Easy"),
 ("evaluate-reverse-polish-notation","Evaluate Reverse Polish Notation","Medium"),
 ("generate-parentheses","Generate Parentheses","Medium"),
 ("daily-temperatures","Daily Temperatures","Medium"),
 ("car-fleet","Car Fleet","Medium"),
 ("next-greater-element-i","Next Greater Element I","Easy"),
 ("next-greater-element-ii","Next Greater Element II","Medium"),
 ("asteroid-collision","Asteroid Collision","Medium"),
 ("decode-string","Decode String","Medium"),
 ("simplify-path","Simplify Path","Medium"),
 ("remove-k-digits","Remove K Digits","Medium"),
 ("online-stock-span","Online Stock Span","Medium"),
 ("basic-calculator-ii","Basic Calculator II","Medium"),
 ("largest-rectangle-in-histogram","Largest Rectangle in Histogram","Hard"),
 ("basic-calculator","Basic Calculator","Hard"),
 ("maximal-rectangle","Maximal Rectangle","Hard"),
],
"Binary Search": [
 ("binary-search","Binary Search","Easy"),
 ("search-insert-position","Search Insert Position","Easy"),
 ("first-bad-version","First Bad Version","Easy"),
 ("sqrtx","Sqrt(x)","Easy"),
 ("guess-number-higher-or-lower","Guess Number Higher or Lower","Easy"),
 ("valid-perfect-square","Valid Perfect Square","Easy"),
 ("arranging-coins","Arranging Coins","Easy"),
 ("search-a-2d-matrix","Search a 2D Matrix","Medium"),
 ("koko-eating-bananas","Koko Eating Bananas","Medium"),
 ("find-minimum-in-rotated-sorted-array","Find Minimum in Rotated Sorted Array","Medium"),
 ("search-in-rotated-sorted-array","Search in Rotated Sorted Array","Medium"),
 ("search-in-rotated-sorted-array-ii","Search in Rotated Sorted Array II","Medium"),
 ("find-peak-element","Find Peak Element","Medium"),
 ("find-first-and-last-position-of-element-in-sorted-array","Find First and Last Position of Element in Sorted Array","Medium"),
 ("capacity-to-ship-packages-within-d-days","Capacity To Ship Packages Within D Days","Medium"),
 ("kth-smallest-element-in-a-sorted-matrix","Kth Smallest Element in a Sorted Matrix","Medium"),
 ("single-element-in-a-sorted-array","Single Element in a Sorted Array","Medium"),
 ("find-the-duplicate-number","Find the Duplicate Number","Medium"),
 ("minimum-speed-to-arrive-on-time","Minimum Speed to Arrive on Time","Medium"),
 ("split-array-largest-sum","Split Array Largest Sum","Hard"),
 ("median-of-two-sorted-arrays","Median of Two Sorted Arrays","Hard"),
],
"Linked List": [
 ("reverse-linked-list","Reverse Linked List","Easy"),
 ("merge-two-sorted-lists","Merge Two Sorted Lists","Easy"),
 ("linked-list-cycle","Linked List Cycle","Easy"),
 ("middle-of-the-linked-list","Middle of the Linked List","Easy"),
 ("remove-linked-list-elements","Remove Linked List Elements","Easy"),
 ("remove-duplicates-from-sorted-list","Remove Duplicates from Sorted List","Easy"),
 ("palindrome-linked-list","Palindrome Linked List","Easy"),
 ("intersection-of-two-linked-lists","Intersection of Two Linked Lists","Easy"),
 ("linked-list-cycle-ii","Linked List Cycle II","Medium"),
 ("remove-nth-node-from-end-of-list","Remove Nth Node From End of List","Medium"),
 ("reorder-list","Reorder List","Medium"),
 ("copy-list-with-random-pointer","Copy List with Random Pointer","Medium"),
 ("add-two-numbers","Add Two Numbers","Medium"),
 ("odd-even-linked-list","Odd Even Linked List","Medium"),
 ("swap-nodes-in-pairs","Swap Nodes in Pairs","Medium"),
 ("rotate-list","Rotate List","Medium"),
 ("partition-list","Partition List","Medium"),
 ("sort-list","Sort List","Medium"),
 ("remove-duplicates-from-sorted-list-ii","Remove Duplicates from Sorted List II","Medium"),
 ("design-linked-list","Design Linked List","Medium"),
 ("lru-cache","LRU Cache","Medium"),
 ("merge-k-sorted-lists","Merge k Sorted Lists","Hard"),
 ("reverse-nodes-in-k-group","Reverse Nodes in k-Group","Hard"),
 ("lfu-cache","LFU Cache","Hard"),
],
"Trees": [
 ("invert-binary-tree","Invert Binary Tree","Easy"),
 ("maximum-depth-of-binary-tree","Maximum Depth of Binary Tree","Easy"),
 ("diameter-of-binary-tree","Diameter of Binary Tree","Easy"),
 ("balanced-binary-tree","Balanced Binary Tree","Easy"),
 ("same-tree","Same Tree","Easy"),
 ("subtree-of-another-tree","Subtree of Another Tree","Easy"),
 ("symmetric-tree","Symmetric Tree","Easy"),
 ("path-sum","Path Sum","Easy"),
 ("minimum-depth-of-binary-tree","Minimum Depth of Binary Tree","Easy"),
 ("binary-tree-inorder-traversal","Binary Tree Inorder Traversal","Easy"),
 ("binary-tree-preorder-traversal","Binary Tree Preorder Traversal","Easy"),
 ("binary-tree-postorder-traversal","Binary Tree Postorder Traversal","Easy"),
 ("average-of-levels-in-binary-tree","Average of Levels in Binary Tree","Easy"),
 ("convert-sorted-array-to-binary-search-tree","Convert Sorted Array to Binary Search Tree","Easy"),
 ("search-in-a-binary-search-tree","Search in a Binary Search Tree","Easy"),
 ("range-sum-of-bst","Range Sum of BST","Easy"),
 ("lowest-common-ancestor-of-a-binary-search-tree","Lowest Common Ancestor of a BST","Medium"),
 ("binary-tree-level-order-traversal","Binary Tree Level Order Traversal","Medium"),
 ("binary-tree-level-order-traversal-ii","Binary Tree Level Order Traversal II","Medium"),
 ("binary-tree-zigzag-level-order-traversal","Binary Tree Zigzag Level Order Traversal","Medium"),
 ("binary-tree-right-side-view","Binary Tree Right Side View","Medium"),
 ("count-good-nodes-in-binary-tree","Count Good Nodes in Binary Tree","Medium"),
 ("validate-binary-search-tree","Validate Binary Search Tree","Medium"),
 ("kth-smallest-element-in-a-bst","Kth Smallest Element in a BST","Medium"),
 ("construct-binary-tree-from-preorder-and-inorder-traversal","Construct Binary Tree from Preorder and Inorder Traversal","Medium"),
 ("path-sum-ii","Path Sum II","Medium"),
 ("path-sum-iii","Path Sum III","Medium"),
 ("sum-root-to-leaf-numbers","Sum Root to Leaf Numbers","Medium"),
 ("flatten-binary-tree-to-linked-list","Flatten Binary Tree to Linked List","Medium"),
 ("populating-next-right-pointers-in-each-node","Populating Next Right Pointers in Each Node","Medium"),
 ("insert-into-a-binary-search-tree","Insert into a Binary Search Tree","Medium"),
 ("delete-node-in-a-bst","Delete Node in a BST","Medium"),
 ("binary-search-tree-iterator","Binary Search Tree Iterator","Medium"),
 ("all-nodes-distance-k-in-binary-tree","All Nodes Distance K in Binary Tree","Medium"),
 ("house-robber-iii","House Robber III","Medium"),
 ("maximum-width-of-binary-tree","Maximum Width of Binary Tree","Medium"),
 ("lowest-common-ancestor-of-a-binary-tree","Lowest Common Ancestor of a Binary Tree","Medium"),
 ("binary-tree-maximum-path-sum","Binary Tree Maximum Path Sum","Hard"),
 ("serialize-and-deserialize-binary-tree","Serialize and Deserialize Binary Tree","Hard"),
],
"Tries": [
 ("implement-trie-prefix-tree","Implement Trie (Prefix Tree)","Medium"),
 ("design-add-and-search-words-data-structure","Design Add and Search Words Data Structure","Medium"),
 ("replace-words","Replace Words","Medium"),
 ("map-sum-pairs","Map Sum Pairs","Medium"),
 ("maximum-xor-of-two-numbers-in-an-array","Maximum XOR of Two Numbers in an Array","Medium"),
 ("word-search-ii","Word Search II","Hard"),
],
"Heap / Priority Queue": [
 ("kth-largest-element-in-a-stream","Kth Largest Element in a Stream","Easy"),
 ("last-stone-weight","Last Stone Weight","Easy"),
 ("k-closest-points-to-origin","K Closest Points to Origin","Medium"),
 ("kth-largest-element-in-an-array","Kth Largest Element in an Array","Medium"),
 ("task-scheduler","Task Scheduler","Medium"),
 ("design-twitter","Design Twitter","Medium"),
 ("top-k-frequent-words","Top K Frequent Words","Medium"),
 ("reorganize-string","Reorganize String","Medium"),
 ("ipo","IPO","Hard"),
 ("single-threaded-cpu","Single-Threaded CPU","Medium"),
 ("seat-reservation-manager","Seat Reservation Manager","Medium"),
 ("find-median-from-data-stream","Find Median from Data Stream","Hard"),
 ("sliding-window-median","Sliding Window Median","Hard"),
],
"Backtracking": [
 ("subsets","Subsets","Medium"),
 ("subsets-ii","Subsets II","Medium"),
 ("combinations","Combinations","Medium"),
 ("combination-sum","Combination Sum","Medium"),
 ("combination-sum-ii","Combination Sum II","Medium"),
 ("combination-sum-iii","Combination Sum III","Medium"),
 ("permutations","Permutations","Medium"),
 ("permutations-ii","Permutations II","Medium"),
 ("word-search","Word Search","Medium"),
 ("palindrome-partitioning","Palindrome Partitioning","Medium"),
 ("letter-combinations-of-a-phone-number","Letter Combinations of a Phone Number","Medium"),
 ("restore-ip-addresses","Restore IP Addresses","Medium"),
 ("partition-to-k-equal-sum-subsets","Partition to K Equal Sum Subsets","Medium"),
 ("beautiful-arrangement","Beautiful Arrangement","Medium"),
 ("n-queens","N-Queens","Hard"),
 ("n-queens-ii","N-Queens II","Hard"),
 ("sudoku-solver","Sudoku Solver","Hard"),
],
"Graphs": [
 ("flood-fill","Flood Fill","Easy"),
 ("find-if-path-exists-in-graph","Find if Path Exists in Graph","Easy"),
 ("number-of-islands","Number of Islands","Medium"),
 ("clone-graph","Clone Graph","Medium"),
 ("max-area-of-island","Max Area of Island","Medium"),
 ("pacific-atlantic-water-flow","Pacific Atlantic Water Flow","Medium"),
 ("surrounded-regions","Surrounded Regions","Medium"),
 ("rotting-oranges","Rotting Oranges","Medium"),
 ("course-schedule","Course Schedule","Medium"),
 ("course-schedule-ii","Course Schedule II","Medium"),
 ("01-matrix","01 Matrix","Medium"),
 ("keys-and-rooms","Keys and Rooms","Medium"),
 ("all-paths-from-source-to-target","All Paths From Source to Target","Medium"),
 ("is-graph-bipartite","Is Graph Bipartite?","Medium"),
 ("evaluate-division","Evaluate Division","Medium"),
 ("number-of-provinces","Number of Provinces","Medium"),
 ("shortest-path-in-binary-matrix","Shortest Path in Binary Matrix","Medium"),
 ("open-the-lock","Open the Lock","Medium"),
 ("minimum-height-trees","Minimum Height Trees","Medium"),
 ("reconstruct-itinerary","Reconstruct Itinerary","Hard"),
 ("cheapest-flights-within-k-stops","Cheapest Flights Within K Stops","Medium"),
 ("network-delay-time","Network Delay Time","Medium"),
 ("path-with-minimum-effort","Path With Minimum Effort","Medium"),
 ("min-cost-to-connect-all-points","Min Cost to Connect All Points","Medium"),
 ("snakes-and-ladders","Snakes and Ladders","Medium"),
 ("nearest-exit-from-entrance-in-maze","Nearest Exit from Entrance in Maze","Medium"),
 ("detonate-the-maximum-bombs","Detonate the Maximum Bombs","Medium"),
 ("word-ladder","Word Ladder","Hard"),
 ("swim-in-rising-water","Swim in Rising Water","Hard"),
 ("longest-increasing-path-in-a-matrix","Longest Increasing Path in a Matrix","Hard"),
],
"Union Find": [
 ("redundant-connection","Redundant Connection","Medium"),
 ("accounts-merge","Accounts Merge","Medium"),
 ("most-stones-removed-with-same-row-or-column","Most Stones Removed with Same Row or Column","Medium"),
 ("satisfiability-of-equality-equations","Satisfiability of Equality Equations","Medium"),
 ("number-of-operations-to-make-network-connected","Number of Operations to Make Network Connected","Medium"),
 ("smallest-string-with-swaps","Smallest String With Swaps","Medium"),
],
"1-D Dynamic Programming": [
 ("climbing-stairs","Climbing Stairs","Easy"),
 ("min-cost-climbing-stairs","Min Cost Climbing Stairs","Easy"),
 ("fibonacci-number","Fibonacci Number","Easy"),
 ("n-th-tribonacci-number","N-th Tribonacci Number","Easy"),
 ("house-robber","House Robber","Medium"),
 ("house-robber-ii","House Robber II","Medium"),
 ("decode-ways","Decode Ways","Medium"),
 ("coin-change","Coin Change","Medium"),
 ("coin-change-ii","Coin Change II","Medium"),
 ("word-break","Word Break","Medium"),
 ("longest-increasing-subsequence","Longest Increasing Subsequence","Medium"),
 ("partition-equal-subset-sum","Partition Equal Subset Sum","Medium"),
 ("delete-and-earn","Delete and Earn","Medium"),
 ("jump-game","Jump Game","Medium"),
 ("jump-game-ii","Jump Game II","Medium"),
 ("best-time-to-buy-and-sell-stock-with-cooldown","Best Time to Buy and Sell Stock with Cooldown","Medium"),
 ("target-sum","Target Sum","Medium"),
 ("combination-sum-iv","Combination Sum IV","Medium"),
 ("perfect-squares","Perfect Squares","Medium"),
 ("integer-break","Integer Break","Medium"),
 ("wiggle-subsequence","Wiggle Subsequence","Medium"),
 ("number-of-longest-increasing-subsequence","Number of Longest Increasing Subsequence","Medium"),
 ("maximum-length-of-pair-chain","Maximum Length of Pair Chain","Medium"),
 ("last-stone-weight-ii","Last Stone Weight II","Medium"),
 ("russian-doll-envelopes","Russian Doll Envelopes","Hard"),
],
"2-D Dynamic Programming": [
 ("unique-paths","Unique Paths","Medium"),
 ("unique-paths-ii","Unique Paths II","Medium"),
 ("minimum-path-sum","Minimum Path Sum","Medium"),
 ("triangle","Triangle","Medium"),
 ("maximal-square","Maximal Square","Medium"),
 ("minimum-falling-path-sum","Minimum Falling Path Sum","Medium"),
 ("count-square-submatrices-with-all-ones","Count Square Submatrices with All Ones","Medium"),
 ("longest-common-subsequence","Longest Common Subsequence","Medium"),
 ("longest-palindromic-subsequence","Longest Palindromic Subsequence","Medium"),
 ("edit-distance","Edit Distance","Medium"),
 ("interleaving-string","Interleaving String","Medium"),
 ("ones-and-zeroes","Ones and Zeroes","Medium"),
 ("best-time-to-buy-and-sell-stock-with-transaction-fee","Best Time to Buy and Sell Stock with Transaction Fee","Medium"),
 ("best-time-to-buy-and-sell-stock-iii","Best Time to Buy and Sell Stock III","Hard"),
 ("best-time-to-buy-and-sell-stock-iv","Best Time to Buy and Sell Stock IV","Hard"),
 ("distinct-subsequences","Distinct Subsequences","Hard"),
 ("burst-balloons","Burst Balloons","Hard"),
 ("regular-expression-matching","Regular Expression Matching","Hard"),
 ("wildcard-matching","Wildcard Matching","Hard"),
 ("dungeon-game","Dungeon Game","Hard"),
],
"Greedy": [
 ("assign-cookies","Assign Cookies","Easy"),
 ("lemonade-change","Lemonade Change","Easy"),
 ("best-time-to-buy-and-sell-stock-ii","Best Time to Buy and Sell Stock II","Medium"),
 ("gas-station","Gas Station","Medium"),
 ("hand-of-straights","Hand of Straights","Medium"),
 ("merge-triplets-to-form-target-triplet","Merge Triplets to Form Target Triplet","Medium"),
 ("valid-parenthesis-string","Valid Parenthesis String","Medium"),
 ("queue-reconstruction-by-height","Queue Reconstruction by Height","Medium"),
 ("candy","Candy","Hard"),
],
"Intervals": [
 ("insert-interval","Insert Interval","Medium"),
 ("merge-intervals","Merge Intervals","Medium"),
 ("non-overlapping-intervals","Non-overlapping Intervals","Medium"),
 ("minimum-number-of-arrows-to-burst-balloons","Minimum Number of Arrows to Burst Balloons","Medium"),
 ("interval-list-intersections","Interval List Intersections","Medium"),
 ("my-calendar-i","My Calendar I","Medium"),
],
"Bit Manipulation": [
 ("number-of-1-bits","Number of 1 Bits","Easy"),
 ("counting-bits","Counting Bits","Easy"),
 ("reverse-bits","Reverse Bits","Easy"),
 ("power-of-two","Power of Two","Easy"),
 ("power-of-four","Power of Four","Easy"),
 ("hamming-distance","Hamming Distance","Easy"),
 ("add-digits","Add Digits","Easy"),
 ("single-number-ii","Single Number II","Medium"),
 ("single-number-iii","Single Number III","Medium"),
 ("sum-of-two-integers","Sum of Two Integers","Medium"),
 ("bitwise-and-of-numbers-range","Bitwise AND of Numbers Range","Medium"),
 ("total-hamming-distance","Total Hamming Distance","Medium"),
],
"Math & Geometry": [
 ("palindrome-number","Palindrome Number","Easy"),
 ("happy-number","Happy Number","Easy"),
 ("excel-sheet-column-title","Excel Sheet Column Title","Easy"),
 ("excel-sheet-column-number","Excel Sheet Column Number","Easy"),
 ("ugly-number","Ugly Number","Easy"),
 ("rectangle-overlap","Rectangle Overlap","Easy"),
 ("reverse-integer","Reverse Integer","Medium"),
 ("powx-n","Pow(x, n)","Medium"),
 ("factorial-trailing-zeroes","Factorial Trailing Zeroes","Medium"),
 ("count-primes","Count Primes","Medium"),
 ("detect-squares","Detect Squares","Medium"),
],
}

EXTRA = {
"Arrays & Hashing": [
 ("concatenation-of-array","Concatenation of Array","Easy"),
 ("build-array-from-permutation","Build Array from Permutation","Easy"),
 ("shuffle-the-array","Shuffle the Array","Easy"),
 ("richest-customer-wealth","Richest Customer Wealth","Easy"),
 ("kids-with-the-greatest-number-of-candies","Kids With the Greatest Number of Candies","Easy"),
 ("number-of-good-pairs","Number of Good Pairs","Easy"),
 ("how-many-numbers-are-smaller-than-the-current-number","How Many Numbers Are Smaller Than the Current Number","Easy"),
 ("sort-array-by-parity","Sort Array By Parity","Easy"),
 ("find-the-highest-altitude","Find the Highest Altitude","Easy"),
 ("maximum-number-of-balloons","Maximum Number of Balloons","Easy"),
 ("check-if-the-sentence-is-pangram","Check if the Sentence Is Pangram","Easy"),
 ("count-items-matching-a-rule","Count Items Matching a Rule","Easy"),
 ("degree-of-an-array","Degree of an Array","Easy"),
 ("longest-harmonious-subsequence","Longest Harmonious Subsequence","Easy"),
 ("find-the-difference-of-two-arrays","Find the Difference of Two Arrays","Easy"),
 ("design-hashmap","Design HashMap","Easy"),
 ("design-hashset","Design HashSet","Easy"),
 ("subarray-product-less-than-k","Subarray Product Less Than K","Medium"),
 ("continuous-subarray-sum","Continuous Subarray Sum","Medium"),
 ("subarray-sums-divisible-by-k","Subarray Sums Divisible by K","Medium"),
 ("k-diff-pairs-in-an-array","K-diff Pairs in an Array","Medium"),
 ("array-nesting","Array Nesting","Medium"),
 ("sort-an-array","Sort an Array","Medium"),
 ("h-index","H-Index","Medium"),
 ("game-of-life","Game of Life","Medium"),
 ("insert-delete-getrandom-o1","Insert Delete GetRandom O(1)","Medium"),
],
"Two Pointers": [
 ("merge-strings-alternately","Merge Strings Alternately","Easy"),
 ("reverse-vowels-of-a-string","Reverse Vowels of a String","Easy"),
 ("sort-array-by-parity-ii","Sort Array By Parity II","Easy"),
 ("remove-duplicates-from-sorted-array-ii","Remove Duplicates from Sorted Array II","Medium"),
 ("string-compression","String Compression","Medium"),
 ("shortest-unsorted-continuous-subarray","Shortest Unsorted Continuous Subarray","Medium"),
 ("dota2-senate","Dota2 Senate","Medium"),
],
"Sliding Window": [
 ("maximum-number-of-vowels-in-a-substring-of-given-length","Maximum Number of Vowels in a Substring of Given Length","Medium"),
 ("number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold","Number of Sub-arrays of Size K and Average >= Threshold","Medium"),
 ("maximum-erasure-value","Maximum Erasure Value","Medium"),
 ("count-number-of-nice-subarrays","Count Number of Nice Subarrays","Medium"),
 ("minimum-operations-to-reduce-x-to-zero","Minimum Operations to Reduce X to Zero","Medium"),
 ("grumpy-bookstore-owner","Grumpy Bookstore Owner","Medium"),
],
"Strings": [
 ("jewels-and-stones","Jewels and Stones","Easy"),
 ("defanging-an-ip-address","Defanging an IP Address","Easy"),
 ("goal-parser-interpretation","Goal Parser Interpretation","Easy"),
 ("detect-capital-use","Detect Capital","Easy"),
 ("valid-palindrome-ii","Valid Palindrome II","Easy"),
 ("longest-palindrome","Longest Palindrome","Easy"),
 ("add-strings","Add Strings","Easy"),
 ("reverse-string-ii","Reverse String II","Easy"),
 ("reverse-words-in-a-string-iii","Reverse Words in a String III","Easy"),
 ("rotate-string","Rotate String","Easy"),
 ("largest-number","Largest Number","Medium"),
 ("compare-version-numbers","Compare Version Numbers","Medium"),
 ("text-justification","Text Justification","Hard"),
],
"Stack": [
 ("make-the-string-great","Make The String Great","Easy"),
 ("remove-all-adjacent-duplicates-in-string","Remove All Adjacent Duplicates In String","Easy"),
 ("removing-stars-from-a-string","Removing Stars From a String","Medium"),
 ("minimum-remove-to-make-valid-parentheses","Minimum Remove to Make Valid Parentheses","Medium"),
 ("132-pattern","132 Pattern","Medium"),
 ("sum-of-subarray-minimums","Sum of Subarray Minimums","Medium"),
 ("longest-valid-parentheses","Longest Valid Parentheses","Hard"),
],
"Binary Search": [
 ("kth-missing-positive-number","Kth Missing Positive Number","Easy"),
 ("peak-index-in-a-mountain-array","Peak Index in a Mountain Array","Medium"),
 ("search-a-2d-matrix-ii","Search a 2D Matrix II","Medium"),
 ("h-index-ii","H-Index II","Medium"),
 ("find-k-closest-elements","Find K Closest Elements","Medium"),
 ("minimum-number-of-days-to-make-m-bouquets","Minimum Number of Days to Make m Bouquets","Medium"),
 ("magnetic-force-between-two-balls","Magnetic Force Between Two Balls","Medium"),
],
"Linked List": [
 ("convert-binary-number-in-a-linked-list-to-integer","Convert Binary Number in a Linked List to Integer","Easy"),
 ("delete-node-in-a-linked-list","Delete Node in a Linked List","Medium"),
 ("insertion-sort-list","Insertion Sort List","Medium"),
 ("split-linked-list-in-parts","Split Linked List in Parts","Medium"),
 ("add-two-numbers-ii","Add Two Numbers II","Medium"),
 ("design-browser-history","Design Browser History","Medium"),
],
"Trees": [
 ("n-ary-tree-preorder-traversal","N-ary Tree Preorder Traversal","Easy"),
 ("n-ary-tree-postorder-traversal","N-ary Tree Postorder Traversal","Easy"),
 ("maximum-depth-of-n-ary-tree","Maximum Depth of N-ary Tree","Easy"),
 ("merge-two-binary-trees","Merge Two Binary Trees","Easy"),
 ("binary-tree-paths","Binary Tree Paths","Easy"),
 ("sum-of-left-leaves","Sum of Left Leaves","Easy"),
 ("minimum-absolute-difference-in-bst","Minimum Absolute Difference in BST","Easy"),
 ("two-sum-iv-input-is-a-bst","Two Sum IV - Input is a BST","Easy"),
 ("increasing-order-search-tree","Increasing Order Search Tree","Easy"),
 ("count-complete-tree-nodes","Count Complete Tree Nodes","Easy"),
 ("construct-binary-tree-from-inorder-and-postorder-traversal","Construct Binary Tree from Inorder and Postorder Traversal","Medium"),
 ("find-bottom-left-tree-value","Find Bottom Left Tree Value","Medium"),
 ("deepest-leaves-sum","Deepest Leaves Sum","Medium"),
 ("recover-binary-search-tree","Recover Binary Search Tree","Medium"),
 ("unique-binary-search-trees","Unique Binary Search Trees","Medium"),
 ("unique-binary-search-trees-ii","Unique Binary Search Trees II","Medium"),
 ("vertical-order-traversal-of-a-binary-tree","Vertical Order Traversal of a Binary Tree","Hard"),
 ("binary-tree-cameras","Binary Tree Cameras","Hard"),
],
"Tries": [
 ("longest-word-in-dictionary","Longest Word in Dictionary","Medium"),
 ("implement-magic-dictionary","Implement Magic Dictionary","Medium"),
 ("search-suggestions-system","Search Suggestions System","Medium"),
 ("prefix-and-suffix-search","Prefix and Suffix Search","Hard"),
],
"Heap / Priority Queue": [
 ("smallest-number-in-infinite-set","Smallest Number in Infinite Set","Medium"),
 ("maximal-score-after-applying-k-operations","Maximal Score After Applying K Operations","Medium"),
 ("total-cost-to-hire-k-workers","Total Cost to Hire K Workers","Medium"),
 ("furthest-building-you-can-reach","Furthest Building You Can Reach","Medium"),
 ("maximum-subsequence-score","Maximum Subsequence Score","Medium"),
 ("minimum-cost-to-hire-k-workers","Minimum Cost to Hire K Workers","Hard"),
],
"Backtracking": [
 ("binary-watch","Binary Watch","Easy"),
 ("letter-case-permutation","Letter Case Permutation","Medium"),
 ("matchsticks-to-square","Matchsticks to Square","Medium"),
 ("split-a-string-into-the-max-number-of-unique-substrings","Split a String Into the Max Number of Unique Substrings","Medium"),
 ("word-break-ii","Word Break II","Hard"),
],
"Graphs": [
 ("find-center-of-star-graph","Find Center of Star Graph","Easy"),
 ("find-the-town-judge","Find the Town Judge","Easy"),
 ("number-of-enclaves","Number of Enclaves","Medium"),
 ("count-sub-islands","Count Sub Islands","Medium"),
 ("shortest-bridge","Shortest Bridge","Medium"),
 ("as-far-from-land-as-possible","As Far from Land as Possible","Medium"),
 ("time-needed-to-inform-all-employees","Time Needed to Inform All Employees","Medium"),
 ("minimum-number-of-vertices-to-reach-all-nodes","Minimum Number of Vertices to Reach All Nodes","Medium"),
 ("possible-bipartition","Possible Bipartition","Medium"),
 ("path-with-maximum-probability","Path with Maximum Probability","Medium"),
 ("find-eventual-safe-states","Find Eventual Safe States","Medium"),
 ("course-schedule-iv","Course Schedule IV","Medium"),
 ("bus-routes","Bus Routes","Hard"),
 ("word-ladder-ii","Word Ladder II","Hard"),
],
"Union Find": [
 ("regions-cut-by-slashes","Regions Cut By Slashes","Medium"),
 ("checking-existence-of-edge-length-limited-paths","Checking Existence of Edge Length Limited Paths","Hard"),
 ("remove-max-number-of-edges-to-keep-graph-fully-traversable","Remove Max Number of Edges to Keep Graph Fully Traversable","Hard"),
],
"1-D Dynamic Programming": [
 ("pascals-triangle-ii","Pascal's Triangle II","Easy"),
 ("longest-arithmetic-subsequence-of-given-difference","Longest Arithmetic Subsequence of Given Difference","Medium"),
 ("stone-game","Stone Game","Medium"),
 ("minimum-cost-for-tickets","Minimum Cost For Tickets","Medium"),
 ("filling-bookcase-shelves","Filling Bookcase Shelves","Medium"),
 ("solving-questions-with-brainpower","Solving Questions With Brainpower","Medium"),
 ("count-sorted-vowel-strings","Count Sorted Vowel Strings","Medium"),
 ("frog-jump","Frog Jump","Hard"),
],
"2-D Dynamic Programming": [
 ("number-of-dice-rolls-with-target-sum","Number of Dice Rolls With Target Sum","Medium"),
 ("knight-probability-in-chessboard","Knight Probability in Chessboard","Medium"),
 ("out-of-boundary-paths","Out of Boundary Paths","Medium"),
 ("cherry-pickup-ii","Cherry Pickup II","Hard"),
 ("palindrome-partitioning-ii","Palindrome Partitioning II","Hard"),
 ("shortest-common-supersequence","Shortest Common Supersequence","Hard"),
 ("max-dot-product-of-two-subsequences","Max Dot Product of Two Subsequences","Hard"),
 ("cherry-pickup","Cherry Pickup","Hard"),
],
"Greedy": [
 ("maximum-units-on-a-truck","Maximum Units on a Truck","Easy"),
 ("minimum-number-of-moves-to-seat-everyone","Minimum Number of Moves to Seat Everyone","Easy"),
 ("two-city-scheduling","Two City Scheduling","Medium"),
 ("car-pooling","Car Pooling","Medium"),
 ("minimum-deletions-to-make-character-frequencies-unique","Minimum Deletions to Make Character Frequencies Unique","Medium"),
 ("maximum-number-of-events-that-can-be-attended","Maximum Number of Events That Can Be Attended","Medium"),
 ("minimum-number-of-refueling-stops","Minimum Number of Refueling Stops","Hard"),
],
"Intervals": [
 ("remove-covered-intervals","Remove Covered Intervals","Medium"),
 ("my-calendar-ii","My Calendar II","Medium"),
 ("data-stream-as-disjoint-intervals","Data Stream as Disjoint Intervals","Hard"),
],
"Bit Manipulation": [
 ("binary-number-with-alternating-bits","Binary Number with Alternating Bits","Easy"),
 ("number-complement","Number Complement","Easy"),
 ("complement-of-base-10-integer","Complement of Base 10 Integer","Easy"),
 ("xor-operation-in-an-array","XOR Operation in an Array","Easy"),
 ("decode-xored-array","Decode XORed Array","Easy"),
 ("gray-code","Gray Code","Medium"),
 ("divide-two-integers","Divide Two Integers","Medium"),
],
"Math & Geometry": [
 ("fizz-buzz","Fizz Buzz","Easy"),
 ("perfect-number","Perfect Number","Easy"),
 ("self-dividing-numbers","Self Dividing Numbers","Easy"),
 ("nim-game","Nim Game","Easy"),
 ("robot-return-to-origin","Robot Return to Origin","Easy"),
 ("max-points-on-a-line","Max Points on a Line","Hard"),
 ("integer-to-english-words","Integer to English Words","Hard"),
],
}

for _t, _items in EXTRA.items():
    POOL[_t].extend(_items)

if __name__ == "__main__":
    total = 0
    seen = set()
    dupes = []
    for topic, items in POOL.items():
        total += len(items)
        for slug, title, diff in items:
            if slug in seen:
                dupes.append(slug)
            seen.add(slug)
    print("topics:", len(POOL))
    print("total entries:", total)
    print("unique slugs:", len(seen))
    print("cross-topic dupes:", dupes)
    for t, i in POOL.items():
        print(f"  {t}: {len(i)}")
