/**
 * AI/ML interview questions — the bank the AI interviewer draws from.
 *
 * DISJOINT from the practice bank in aimlPracticeBank.ts, asserted by the
 * generator. Practising the questions you are then interviewed on turns the
 * interview into a memory test.
 *
 * ML has no judge. Every question carries a rubric so you can grade yourself
 * after the attempt — that mechanism is the entire point.
 *
 * GENERATED by scripts/gen-aiml-practice.cjs — edit that, not this.
 */
import type { QTier, SdQuestion } from './sdPractice'

/**
 * Graded on every AI/ML question. Deliberately different from the system design
 * rubric: the failure modes here are about data, labels and feedback loops, not
 * about sharding.
 */
export const AIML_UNIVERSAL_RUBRIC: string[] = [
  'Framed it as a prediction task: named the input, the label, and the unit of prediction',
  'Named the offline metric you optimise AND the online metric the business cares about',
  'Said where training data and labels come from, including how delayed or biased they are',
  'Named the baseline you have to beat — ideally one with no ML in it',
  'Separated training from serving, and said what must hold in each',
  'Stated a latency and cost budget with numbers, and respected it later',
  'Said how you would detect this breaking in production when labels are missing or late',
]

export const AIML_INTERVIEW: SdQuestion[] = [
  {
    id: "i-newsfeed-rank",
    title: "Rank a news feed",
    tier: "core",
    family: "design",
    scope: "Order posts for a social feed with 100M daily users.",
    clarify: [
      "What is the objective — engagement, time, or something else?",
      "How fresh must it be?",
      "Latency budget?",
    ],
    rubric: [
      "Candidate generation and ranking separated",
      "Objective defined before any modelling",
      "Freshness vs relevance tension addressed",
      "Feedback loop and filter-bubble risk named",
      "Cold start for new posts",
    ],
  },
  {
    id: "i-churn",
    title: "Predict subscriber churn",
    tier: "core",
    family: "design",
    scope: "Flag subscribers likely to cancel within 30 days.",
    clarify: [
      "What action follows a prediction?",
      "How is churn defined exactly?",
      "Label delay?",
    ],
    rubric: [
      "Prediction window and label definition pinned down",
      "The intervention determines the metric, not the other way round",
      "Survivorship and censoring in the training data",
      "Uplift vs raw propensity distinguished",
      "Cost of a wasted retention offer",
    ],
  },
  {
    id: "i-duplicate-detect",
    title: "Detect duplicate listings",
    tier: "core",
    family: "design",
    scope: "Find duplicate product listings across 100M items.",
    clarify: [
      "Exact or near duplicates?",
      "Text, image, or both?",
      "Batch or real-time?",
    ],
    rubric: [
      "Blocking / candidate generation before pairwise comparison",
      "Embedding plus ANN for the candidate stage",
      "Threshold tuned against a labelled pair set",
      "Transitivity problem when merging clusters",
      "Human review for the ambiguous band",
    ],
  },
  {
    id: "i-support-triage",
    title: "Route support tickets",
    tier: "core",
    family: "design",
    scope: "Send incoming tickets to the right team automatically.",
    clarify: [
      "How many teams?",
      "Cost of a misroute?",
      "Is there historical routing data?",
    ],
    rubric: [
      "Historical routing as labels, and the bias that carries",
      "Confidence threshold with a fallback to manual",
      "Class imbalance across teams",
      "Feedback captured when a human reroutes",
      "New team / new category handling",
    ],
  },
  {
    id: "i-doc-qa",
    title: "Question answering over documents",
    tier: "core",
    family: "design",
    scope: "Answer employee questions over internal wikis and PDFs.",
    clarify: [
      "Are permissions per-document?",
      "How stale can answers be?",
      "Is refusal acceptable?",
    ],
    rubric: [
      "Permission filtering applied at retrieval, not after generation",
      "Chunking and parsing of heterogeneous formats",
      "Grounding with citations",
      "Refusal behaviour when nothing relevant is retrieved",
      "Evaluation of retrieval separate from answers",
    ],
  },
  {
    id: "i-spam",
    title: "Design a spam filter",
    tier: "core",
    family: "design",
    scope: "Filter spam for a messaging product under adversarial pressure.",
    clarify: [
      "False positive cost?",
      "How fast do attackers adapt?",
      "Any user reporting?",
    ],
    rubric: [
      "Adversarial adaptation as the central constraint",
      "Fast-updating rules alongside a slower model",
      "User reports as a label source, and their noise",
      "Precision priority because false positives lose messages",
      "Shadow evaluation before enforcement",
    ],
  },
  {
    id: "i-speech",
    title: "Design speech transcription serving",
    tier: "hard",
    family: "design",
    scope: "Transcribe audio at scale, both streaming and batch.",
    clarify: [
      "Streaming or offline?",
      "How many languages?",
      "Accuracy target?",
    ],
    rubric: [
      "Streaming vs batch as genuinely different systems",
      "Chunking with overlap for streaming, and boundary errors",
      "WER as the metric, with its limitations",
      "GPU batching for the offline path",
      "Fallback and retry for long audio",
    ],
  },
  {
    id: "i-image-search",
    title: "Design visual search",
    tier: "hard",
    family: "design",
    scope: "Find visually similar products from a user photo.",
    clarify: [
      "Catalogue size?",
      "Latency budget?",
      "Is text also available?",
    ],
    rubric: [
      "Embedding model plus ANN index",
      "Index type and its memory/recall tradeoff",
      "Multimodal fusion if text exists",
      "Query-image preprocessing and its failure modes",
      "Evaluation set of query/target pairs",
    ],
  },
  {
    id: "i-forecast",
    title: "Forecast demand",
    tier: "core",
    family: "design",
    scope: "Predict daily demand per SKU per warehouse.",
    clarify: [
      "How many series?",
      "Horizon?",
      "What decision does it drive?",
    ],
    rubric: [
      "Time-based splitting, never random",
      "Hierarchical structure across SKU and location",
      "Intermittent/sparse series handled",
      "Metric chosen for the decision (over- vs under-stocking cost)",
      "Baseline: last week, seasonal naive",
    ],
  },
  {
    id: "i-pricing",
    title: "Design dynamic pricing",
    tier: "hard",
    family: "design",
    scope: "Set prices that respond to demand without a labelled ground truth.",
    clarify: [
      "Is there exploration budget?",
      "Any fairness or legal constraint?",
      "How fast can prices change?",
    ],
    rubric: [
      "No counterfactual labels — this is a bandit, not supervised learning",
      "Exploration vs exploitation with a real cost",
      "Guardrails and price-change limits",
      "Fairness and legal constraints named explicitly",
      "Offline evaluation via off-policy estimation",
    ],
  },
  {
    id: "i-anomaly",
    title: "Detect infrastructure anomalies",
    tier: "core",
    family: "design",
    scope: "Alert on abnormal service behaviour across thousands of metrics.",
    clarify: [
      "What is the alert budget?",
      "Are there labels?",
      "Seasonality?",
    ],
    rubric: [
      "Unsupervised framing because anomalies are unlabelled",
      "Seasonality and deploy events as expected changes",
      "Alert fatigue as the real failure mode",
      "Per-metric vs joint modelling tradeoff",
      "Feedback from on-call to suppress known-benign patterns",
    ],
  },
  {
    id: "i-translate",
    title: "Serve machine translation",
    tier: "core",
    family: "design",
    scope: "Translate user-generated content across 30 language pairs.",
    clarify: [
      "Latency budget?",
      "Quality bar per language?",
      "Volume skew?",
    ],
    rubric: [
      "One multilingual model vs per-pair models, with the tradeoff",
      "Caching for repeated content",
      "Quality varying by pair and how you measure it",
      "Low-resource languages handled explicitly",
      "Fallback when a pair is unsupported",
    ],
  },
  {
    id: "i-autocomplete",
    title: "Design search autocomplete",
    tier: "core",
    family: "design",
    scope: "Suggest completions within 50ms as the user types.",
    clarify: [
      "Personalised?",
      "How fresh must suggestions be?",
      "Any safety filtering?",
    ],
    rubric: [
      "Latency budget ruling out a large model on the hot path",
      "Prefix index / trie plus a ranking signal",
      "Popularity with recency decay",
      "Safety filtering of suggestions",
      "Cold start for new or rare prefixes",
    ],
  },
  {
    id: "i-copilot",
    title: "Design a code assistant",
    tier: "hard",
    family: "design",
    scope: "Suggest code completions inside an editor.",
    clarify: [
      "Latency budget?",
      "How much context is available?",
      "Is acceptance measured?",
    ],
    rubric: [
      "Time-to-first-token as the metric that matters",
      "Context assembly from the open file and repository",
      "Acceptance rate as the online metric, with its bias",
      "Caching and speculative decoding as latency levers",
      "Privacy of code sent off-machine",
    ],
  },
  {
    id: "i-summarise",
    title: "Summarise long documents",
    tier: "core",
    family: "design",
    scope: "Produce reliable summaries of documents longer than the context window.",
    clarify: [
      "How long are the documents?",
      "Is faithfulness or brevity primary?",
      "Any structure to exploit?",
    ],
    rubric: [
      "Chunk-and-combine strategy, with its failure modes",
      "Faithfulness measured separately from fluency",
      "Hallucination detection or grounding",
      "Cost scaling with document length",
      "Evaluation without reference summaries",
    ],
  },
  {
    id: "i-guardrails",
    title: "Design LLM guardrails",
    tier: "hard",
    family: "design",
    scope: "Prevent unsafe or off-topic outputs in a customer-facing assistant.",
    clarify: [
      "What is actually prohibited?",
      "False positive tolerance?",
      "Latency budget?",
    ],
    rubric: [
      "Input and output filtering as separate stages",
      "Prompt injection treated as untrusted input",
      "Latency cost of an extra model on the path",
      "Escalation and refusal behaviour",
      "Red-teaming and a growing adversarial eval set",
    ],
  },
  {
    id: "i-personalise-email",
    title: "Personalise send timing",
    tier: "core",
    family: "design",
    scope: "Choose when to send each user a notification.",
    clarify: [
      "What is the objective?",
      "Any frequency cap?",
      "Timezone handling?",
    ],
    rubric: [
      "Per-user timing model vs global heuristic baseline",
      "Fatigue and frequency capping as a hard constraint",
      "Objective beyond opens — long-term retention",
      "Exploration to learn timing for new users",
      "Holdout group kept permanently",
    ],
  },
  {
    id: "i-vector-db",
    title: "Choose and size a vector store",
    tier: "hard",
    family: "design",
    scope: "Pick the index for 100M embeddings under a 20ms budget.",
    clarify: [
      "Recall target?",
      "Update rate?",
      "Memory budget?",
    ],
    rubric: [
      "HNSW vs IVF vs flat, with the recall/memory/latency tradeoff",
      "Memory footprint estimated from dimension and count",
      "Update and delete handling in the chosen index",
      "Recall measured against exact search",
      "Sharding when it exceeds one machine",
    ],
  },
  {
    id: "i-multimodal",
    title: "Design multimodal retrieval",
    tier: "hard",
    family: "design",
    scope: "Search a video library by text query.",
    clarify: [
      "What granularity — clip or video?",
      "Volume?",
      "Latency?",
    ],
    rubric: [
      "Frame/clip sampling strategy and its cost",
      "Joint embedding space vs separate indexes",
      "Temporal aggregation to a video-level score",
      "Storage and compute for indexing at scale",
      "Evaluation with real queries",
    ],
  },
  {
    id: "i-experiment-platform",
    title: "Design an ML experiment platform",
    tier: "hard",
    family: "design",
    scope: "Let 50 engineers run and compare model experiments.",
    clarify: [
      "How many runs per day?",
      "Shared compute?",
      "Compliance needs?",
    ],
    rubric: [
      "Run metadata, artefacts and lineage captured automatically",
      "Compute scheduling and quota between teams",
      "Comparability: same eval, same data version",
      "Reproducing a six-month-old run",
      "Cost visibility per team",
    ],
  },
  {
    id: "i-data-quality",
    title: "Design data quality checks",
    tier: "core",
    family: "design",
    scope: "Stop bad upstream data from poisoning a production model.",
    clarify: [
      "How many sources?",
      "Can you block a pipeline?",
      "Who owns upstream?",
    ],
    rubric: [
      "Schema, range, volume and null-rate checks",
      "Failing loudly vs degrading gracefully — chosen deliberately",
      "Distribution checks beyond schema validation",
      "Quarantine rather than silent drop",
      "Ownership and alerting to the upstream team",
    ],
  },
  {
    id: "i-onboard-model",
    title: "Take a notebook to production",
    tier: "core",
    family: "design",
    scope: "A data scientist hands you a notebook that works. Ship it.",
    clarify: [
      "How is it retrained?",
      "What are the dependencies?",
      "Who owns it after?",
    ],
    rubric: [
      "Notebook to reproducible pipeline as the first step",
      "Dependency and environment pinning",
      "Feature computation moved to a shared path",
      "Monitoring and ownership defined before launch",
      "The rollback story",
    ],
  },
  {
    id: "i-cost-cut",
    title: "Halve inference cost",
    tier: "hard",
    family: "design",
    scope: "You are told to cut serving cost by 50% without users noticing.",
    clarify: [
      "Where does the cost actually go?",
      "What quality drop is detectable?",
      "Timeline?",
    ],
    rubric: [
      "Measure before optimising — cost broken down by component",
      "Caching, batching, quantisation, smaller model, routing — ranked by effort",
      "Model routing by difficulty as a large lever",
      "Quality guarded by an eval, not by vibes",
      "A staged plan, not a single change",
    ],
  },
  {
    id: "i-migrate-model",
    title: "Migrate to a new base model",
    tier: "hard",
    family: "design",
    scope: "Move a production LLM feature from one base model to another.",
    clarify: [
      "What changed — cost, quality, or availability?",
      "Are prompts tuned to the old model?",
      "Rollback window?",
    ],
    rubric: [
      "Prompts being overfitted to the old model as the main risk",
      "A/B or shadow comparison on the real eval set",
      "Tokeniser and context window differences",
      "Staged rollout with a kill switch",
      "Cost and latency re-measured, not assumed",
    ],
  },
]

export const AIML_TIERS: QTier[] = ['warmup', 'core', 'hard']

/** Rubric points for an AI/ML question: the shared framework plus its specifics. */
export function aimlRubric(question: SdQuestion): { text: string; universal: boolean }[] {
  return [
    ...AIML_UNIVERSAL_RUBRIC.map((text) => ({ text, universal: true })),
    ...question.rubric.map((text) => ({ text, universal: false })),
  ]
}
