/**
 * System design practice questions.
 *
 * Unlike DSA there is no judge: nothing can tell you whether your answer was
 * good. So every question ships a RUBRIC — the specific points a strong answer
 * covers — and you grade yourself against it after the attempt, not before.
 * That is the whole mechanism; without it "practise system design" is just
 * staring at a whiteboard.
 *
 * GENERATED by scripts/gen-sd-practice.cjs. Reference video ids are resolved
 * by title fragment against scraped playlist data and never typed by hand.
 */
import type { SdVideo, SdReading } from './systemDesign'

export type QTier = 'warmup' | 'core' | 'hard'

export interface SdQuestion {
  id: string
  title: string
  tier: QTier
  /** One line of framing, so you know what you are being asked. */
  scope: string
  /** Questions to ask before designing anything. */
  clarify: string[]
  /** Question-specific points a strong answer hits. Grade yourself on these. */
  rubric: string[]
  /**
   * Which kind of exercise this is. Only the AI/ML banks set it — system design
   * questions are all the same shape, but ML practice mixes explain-the-concept,
   * find-the-bug, design-the-system and work-out-the-cost, and they are not
   * interchangeable.
   */
  family?: string
  video?: SdVideo
  reading?: SdReading
}

const PRIMER = 'https://github.com/donnemartin/system-design-primer'
const primer = (anchor: string, label: string): SdReading => ({
  label,
  url: `${PRIMER}#${anchor}`,
  source: 'System Design Primer',
})

/**
 * Graded on every question — this is the framework itself, so repeating it per
 * question would just be noise.
 */
export const UNIVERSAL_RUBRIC: string[] = [
  'Scoped it: named the functional requirements you are building, and what you are explicitly not',
  'Stated non-functionals with numbers: scale, read/write ratio, latency target, availability',
  'Did back-of-envelope: QPS, storage/year, bandwidth — and used them later',
  'Sketched the API before the boxes',
  'Chose a data model and justified the store against the access pattern',
  'Drew a high-level design that a reader could follow end to end',
  'Named bottlenecks and what you would fix first at 10x',
]

export const SD_QUESTIONS: SdQuestion[] = [
  {
    id: 'url-shortener',
    title: 'URL shortener',
    tier: 'warmup',
    scope: 'Take a long URL, return a short one, redirect on lookup.',
    clarify: [
      'Custom aliases allowed?',
      'Link expiry?',
      'Analytics on clicks?',
      'Read:write ratio — assume heavily read',
    ],
    rubric: [
      'Key generation without cross-server coordination (counter+base62, or hash+collision check)',
      'Explained why a random hash needs a collision check and a counter does not',
      'Redirect is 301 vs 302 — and why 302 keeps analytics working',
      'Read path served from cache; database is the fallback not the front door',
      'Storage estimate justifies the key length you chose',
    ],
    reading: primer('design-pastebincom-or-bitly', 'Design Pastebin / Bit.ly — full walkthrough'),
  },
  {
    id: 'rate-limiter',
    title: 'Rate limiter',
    tier: 'warmup',
    scope: 'Reject requests above a per-user quota, across a fleet of servers.',
    clarify: [
      'Per user, per IP, or per API key?',
      'Hard reject or queue?',
      'Limit shared across regions?',
    ],
    rubric: [
      'Picked an algorithm and named its failure mode (token vs leaky bucket vs sliding window)',
      'Fixed-window burst problem at the boundary, and how sliding window fixes it',
      'Where counters live so many gateway nodes agree — and the race on read-modify-write',
      'What happens when the counter store is down: fail open or fail closed, and why',
      'Returns 429 with Retry-After rather than dropping silently',
    ],
  },
  {
    id: 'key-value-store',
    title: 'Distributed key-value store',
    tier: 'warmup',
    scope: 'A store that survives nodes coming and going.',
    clarify: [
      'Consistency guarantee required?',
      'Durability on write?',
      'Expected value size?',
    ],
    rubric: [
      'Consistent hashing for placement, and why it limits reshuffling',
      'Replication factor N, with quorum R + W > N reasoned about explicitly',
      'How the ring detects failure and what happens to writes during it',
      'Repair after a node returns (read repair / anti-entropy / hinted handoff)',
      'Named the consistency model you are actually offering',
    ],
    video: { id: 'Dwt8R0KPu7k', title: 'How Key value Stores Work (Redis, DynamoDB, Memcached)?', seconds: 360, channel: 'ByteByteGo' },
    reading: primer('design-a-key-value-store-for-a-search-engine', 'Design a key-value store'),
  },
  {
    id: 'unique-id',
    title: 'Unique ID generator',
    tier: 'warmup',
    scope: 'Generate 64-bit ids, sortable by time, across many machines.',
    clarify: [
      'Must ids be strictly monotonic or roughly time-ordered?',
      'How many machines?',
      'Is leaking volume acceptable?',
    ],
    rubric: [
      'Snowflake layout: timestamp + machine id + sequence, with bit budget justified',
      'Why a database auto-increment does not survive sharding',
      'Clock skew and what happens when time moves backwards',
      'How machine ids are assigned without a human doing it',
      'Trade-off named: UUIDv4 is easy but destroys index locality',
    ],
  },
  {
    id: 'news-feed',
    title: 'News feed',
    tier: 'core',
    scope: 'Build the home timeline for a social product.',
    clarify: [
      'Follow graph size — any celebrities?',
      'Chronological or ranked?',
      'How stale may the feed be?',
    ],
    rubric: [
      'Fanout on write vs on read, with the read/write ratio driving the choice',
      'The celebrity problem, and the hybrid that fixes it',
      'Feed cache per user, and what is stored — ids or hydrated posts',
      'Pagination that survives new posts arriving (cursor, not offset)',
      'What is precomputed vs computed at request time',
    ],
    video: { id: 'QmX2NPkJTKg', title: 'Designing INSTAGRAM: System Design of News Feed', seconds: 1440, channel: 'Gaurav Sen' },
    reading: primer('design-the-twitter-timeline-and-search-or-facebook-feed-and-search', 'Design the Twitter timeline'),
  },
  {
    id: 'chat',
    title: 'Chat / messaging',
    tier: 'core',
    scope: 'One-to-one and group messaging with delivery state.',
    clarify: [
      'Group size limit?',
      'Message history retention?',
      'Read receipts and presence needed?',
    ],
    rubric: [
      'Persistent connections (WebSocket) and how a server finds the recipient',
      'Per-conversation ordering — sequence numbers, not wall-clock timestamps',
      'Offline delivery: the inbox/queue that holds messages until pickup',
      'Presence is expensive: how you avoid a fanout storm on every connect',
      'Storage model chosen for "recent messages, one conversation" reads',
    ],
    video: { id: 'okrR1KXNLtA', title: 'FAANG System Design Interview: Design A Chat System (WhatsApp, Facebook Messenger, Discord, Slack)', seconds: 525, channel: 'ByteByteGo' },
  },
  {
    id: 'web-crawler',
    title: 'Web crawler',
    tier: 'core',
    scope: 'Crawl a large slice of the web, repeatedly.',
    clarify: [
      'How many pages, in what window?',
      'Respect robots.txt?',
      'Recrawl policy?',
    ],
    rubric: [
      'URL frontier with politeness — per-domain rate limiting, not global',
      'Deduplication of URLs and of content (checksums, not just URLs)',
      'Trap avoidance: infinite calendars, session ids, redirect loops',
      'Distributed workers pulling from the frontier without duplicating work',
      'Freshness: how a page gets scheduled for recrawl',
    ],
    video: { id: '6u25GckPhLU', title: 'Design a Web Crawler: FAANG Interview Question', seconds: 341, channel: 'ByteByteGo' },
    reading: primer('design-a-web-crawler', 'Design a web crawler'),
  },
  {
    id: 'typeahead',
    title: 'Typeahead / autocomplete',
    tier: 'core',
    scope: 'Suggest completions as the user types.',
    clarify: [
      'Top-k per prefix?',
      'Personalised?',
      'How fresh must suggestions be?',
    ],
    rubric: [
      'Trie with top-k precomputed at each node, not computed per keystroke',
      'Why you debounce on the client before the request ever leaves',
      'Where the trie lives and how it is sharded by prefix',
      'Rebuild pipeline is offline and batched — suggestions are allowed to be stale',
      'Latency budget stated: this is a sub-100ms feature or it is useless',
    ],
  },
  {
    id: 'notification',
    title: 'Notification system',
    tier: 'core',
    scope: 'Fan a single event out to push, email and SMS.',
    clarify: [
      'Which channels?',
      'Delivery guarantee?',
      'User preferences and quiet hours?',
    ],
    rubric: [
      'Queue between the trigger and the senders, so a slow provider cannot block',
      'Per-channel workers with independent retry and rate limits',
      'Idempotency so a retry does not notify twice',
      'Preference and opt-out checked at send time, not at enqueue time',
      'Dead-letter handling for permanently failing sends',
    ],
  },
  {
    id: 'youtube',
    title: 'Video platform',
    tier: 'core',
    scope: 'Upload, process and stream video at scale.',
    clarify: [
      'Max upload size?',
      'Which resolutions?',
      'Live or on-demand?',
    ],
    rubric: [
      'Upload goes to blob storage directly, not through the app server',
      'Transcoding as a queue of jobs, fanned out per resolution',
      'Why the pipeline is a DAG and how a failed step is retried',
      'CDN for delivery, with adaptive bitrate explained',
      'Metadata store separate from blob store, with the access pattern named',
    ],
    video: { id: 'jWRW2xGMqSw', title: 'System Design: Design YouTube', seconds: 433, channel: 'ByteByteGo' },
  },
  {
    id: 'drive',
    title: 'Cloud drive / file sync',
    tier: 'core',
    scope: 'Sync files across a user\'s devices.',
    clarify: [
      'Max file size?',
      'Sharing between users?',
      'Offline edits allowed?',
    ],
    rubric: [
      'Chunking, so a one-byte change does not re-upload a gigabyte',
      'Content-addressed chunks and deduplication',
      'Sync protocol: how a client learns what changed since it last looked',
      'Conflict resolution when two devices edit offline — and who wins',
      'Metadata service separate from chunk storage',
    ],
  },
  {
    id: 'ride-matching',
    title: 'Ride matching',
    tier: 'core',
    scope: 'Match riders to nearby drivers in real time.',
    clarify: [
      'Match radius?',
      'How often do drivers report location?',
      'Surge pricing in scope?',
    ],
    rubric: [
      'Geospatial index — geohash/quadtree/S2 — and why a lat-long B-tree fails',
      'Write volume of location pings, and why they go somewhere cheap',
      'Matching as a short-lived lock so two riders cannot take one driver',
      'State machine for a trip, and where it is persisted',
      'Hot cells: a stadium at closing time, and what you do about it',
    ],
    video: { id: 'M4lR_Va97cQ', title: 'FAANG System Design Interview: Design A Location Based Service (Yelp, Google Places)', seconds: 1440, channel: 'ByteByteGo' },
  },
  {
    id: 'ticket-booking',
    title: 'Ticket booking',
    tier: 'core',
    scope: 'Sell reserved seats under heavy contention.',
    clarify: [
      'Seat selection or general admission?',
      'Hold duration?',
      'Overselling ever acceptable?',
    ],
    rubric: [
      'The double-booking problem stated precisely as a race',
      'Reservation with a TTL hold, then confirm — not a single write',
      'Transaction or conditional update at the row level, with isolation named',
      'Queueing/waiting room for a popular on-sale, so the DB is not the queue',
      'What happens when payment fails after the hold',
    ],
  },
  {
    id: 'payments',
    title: 'Payment system',
    tier: 'core',
    scope: 'Charge a customer and keep books that balance.',
    clarify: [
      'Which payment methods?',
      'Refunds and chargebacks?',
      'Multi-currency?',
    ],
    rubric: [
      'Double-entry ledger, append-only — no UPDATE on a balance',
      'Idempotency key on every charge so retries cannot double-charge',
      'Reconciliation against the provider, and what a mismatch triggers',
      'The dual-write problem between your DB and the provider, and the outbox fix',
      'Money is integer minor units, never a float',
    ],
    video: { id: 'cHv8LqkbPHk', title: 'How Does Apple/Google Pay Work?', seconds: 373, channel: 'ByteByteGo' },
    reading: primer('design-mintcom', 'Design Mint.com'),
  },
  {
    id: 'search',
    title: 'Search engine',
    tier: 'core',
    scope: 'Full-text search over a large corpus.',
    clarify: [
      'Corpus size and update rate?',
      'Ranking signals available?',
      'Typo tolerance?',
    ],
    rubric: [
      'Inverted index: term to posting list, and why that beats scanning',
      'Index build is an offline pipeline, separate from serving',
      'Sharding the index by document, and scatter-gather at query time',
      'Ranking as a second pass over a candidate set, not over everything',
      'Freshness tier for very recent documents',
    ],
    video: { id: 'TByRaraQqW4', title: 'How Search Really Works', seconds: 558, channel: 'ByteByteGo' },
  },
  {
    id: 'metrics',
    title: 'Metrics and monitoring',
    tier: 'core',
    scope: 'Ingest, store and query time-series at scale.',
    clarify: [
      'Retention period?',
      'Query patterns — dashboards or alerts?',
      'Cardinality expectations?',
    ],
    rubric: [
      'Write path optimised for append; why a general-purpose OLTP store is wrong',
      'Rollups/downsampling so a year of per-second data is affordable',
      'Cardinality explosion from labels, and how you bound it',
      'Push vs pull collection, with the trade-off named',
      'Alert evaluation path kept separate from dashboard queries',
    ],
  },
  {
    id: 'distributed-cache',
    title: 'Distributed cache',
    tier: 'hard',
    scope: 'A cache tier shared by many application servers.',
    clarify: [
      'Eviction policy?',
      'Consistency with the source of truth?',
      'Cache size vs working set?',
    ],
    rubric: [
      'Placement via consistent hashing, and what a node loss costs',
      'Invalidation strategy, and why it is the hard half',
      'Stampede protection: locking, or probabilistic early expiry',
      'Hot key problem and replication of just that key',
      'What the application does on a cache-tier outage',
    ],
  },
  {
    id: 'job-scheduler',
    title: 'Distributed job scheduler',
    tier: 'hard',
    scope: 'Run scheduled and one-off jobs across a worker fleet.',
    clarify: [
      'At-least-once or at-most-once?',
      'Max job duration?',
      'Priorities or fairness?',
    ],
    rubric: [
      'Leasing so two workers cannot run one job, with lease renewal',
      'What happens when a worker dies mid-job — and why at-least-once is the honest promise',
      'Idempotency requirement pushed onto the job itself',
      'Backoff and dead-lettering for repeatedly failing jobs',
      'Fairness so one tenant cannot starve the queue',
    ],
  },
  {
    id: 'ad-click',
    title: 'Ad click aggregation',
    tier: 'hard',
    scope: 'Count clicks at very high volume, with reporting.',
    clarify: [
      'Exact or approximate counts?',
      'Reporting latency tolerance?',
      'Fraud filtering in scope?',
    ],
    rubric: [
      'Stream ingestion with a log, not synchronous DB writes',
      'Windowed aggregation, and late-arriving events',
      'Exactly-once is a lie — how you dedupe with event ids instead',
      'Pre-aggregated rollups for the query path',
      'Approximation (HyperLogLog) where exactness is not required, stated as a choice',
    ],
  },
  {
    id: 'leaderboard',
    title: 'Leaderboard',
    tier: 'hard',
    scope: 'Global and friend rankings that update constantly.',
    clarify: [
      'How many players?',
      'Real-time or periodic?',
      'Need "my rank" for everyone?',
    ],
    rubric: [
      'Sorted set for top-N, and why a SQL ORDER BY does not scale here',
      '"My rank" for a mid-table player is the expensive query — how you avoid it',
      'Bucketing/approximate rank as an accepted trade-off',
      'Write amplification when every score updates the structure',
      'Sharding by game/region and merging',
    ],
    video: { id: 'a4yX7RUgTxI', title: 'Top 5 Redis Use Cases', seconds: 388, channel: 'ByteByteGo' },
  },
  {
    id: 'multi-region',
    title: 'Multi-region active-active',
    tier: 'hard',
    scope: 'Serve and accept writes from more than one region.',
    clarify: [
      'Which data must be globally consistent?',
      'RPO/RTO targets?',
      'Regulatory data residency?',
    ],
    rubric: [
      'What you give up: named the CAP trade-off for each data class',
      'Conflict resolution for concurrent writes (LWW, CRDT, or partition by region)',
      'Replication lag made visible to the user, or hidden — and how',
      'Failover: how traffic moves, and what is lost',
      'Why some data (payments, inventory) should stay single-writer',
    ],
  },
  {
    id: 'consistency-tradeoff',
    title: 'Pick the consistency model',
    tier: 'hard',
    scope: 'Given three features, choose a consistency model for each and defend it.',
    clarify: [
      'What does the user actually observe?',
      'What is the cost of being wrong?',
      'Can staleness be hidden?',
    ],
    rubric: [
      'Bank balance: strong, and why eventual is unacceptable here',
      'Social feed: eventual, and why the user cannot tell',
      'Read-your-own-writes for the poster, and how you achieve it cheaply',
      'Named the mechanism, not just the label (quorum, sticky routing, session token)',
      'Said what latency each choice costs',
    ],
    video: { id: 'm4q7VkgDWrM', title: 'Data Consistency and Tradeoffs in Distributed Systems', seconds: 1500, channel: 'Gaurav Sen' },
    reading: primer('consistency-patterns', 'Consistency patterns'),
  },
  {
    id: 'scale-to-millions',
    title: 'Scale a monolith to millions',
    tier: 'hard',
    scope: 'A single server app is buckling. Walk the whole evolution.',
    clarify: [
      'Current bottleneck — CPU, DB, or bandwidth?',
      'Budget?',
      'Acceptable downtime for migration?',
    ],
    rubric: [
      'Ordered the moves by cost/benefit rather than jumping to microservices',
      'Vertical first, then stateless app tier behind a load balancer',
      'Read replicas before sharding, and why sharding is the last resort',
      'Cache and CDN placed where the measurement said, not by reflex',
      'Named what you would measure to know the next bottleneck',
    ],
    reading: primer('design-a-system-that-scales-to-millions-of-users-on-aws', 'Scaling to millions of users'),
  },
  {
    id: 'social-graph',
    title: 'Social graph',
    tier: 'hard',
    scope: 'Store and query a follow/friend graph.',
    clarify: [
      'Directed or mutual?',
      'Max degree?',
      'Which queries dominate?',
    ],
    rubric: [
      'Adjacency storage chosen against the dominant query, both directions',
      'Why a naive JOIN across a sharded graph is the wrong plan',
      'Denormalising follower lists, and the write cost that buys',
      'Two-hop queries (friends of friends) and why you bound them',
      'Handling the very-high-degree node',
    ],
    reading: primer('design-the-data-structures-for-a-social-network', 'Data structures for a social network'),
  },
]

export const TIERS: QTier[] = ['warmup', 'core', 'hard']

/** Rubric points for a question: the shared framework plus its specifics. */
export function allRubric(question: SdQuestion): { text: string; universal: boolean }[] {
  return [
    ...UNIVERSAL_RUBRIC.map((text) => ({ text, universal: true })),
    ...question.rubric.map((text) => ({ text, universal: false })),
  ]
}
